### ISSUE TITLE
Migrate from .env files to TOML/YAML for configuration

### ISSUE THREAD

**Issue by Mavial** [the-globe-v2/news-scraper#8]
Currently, the GlobeNewsScraper project uses `.env` files for configuration. While this works, moving to a more structured format like TOML or YAML could provide several benefits.

## Current Implementation
I use `pydantic_settings` to load configuration from `.env` files:

```python
from pydantic_settings import BaseSettings, SettingsConfigDict

class Config(BaseSettings):
    model_config = SettingsConfigDict(env_file='.env', env_file_encoding='utf-8', extra='ignore')
    # ... configuration fields ...
```

## Proposed Change
Migrate from `.env` files to either TOML or YAML for configuration. This will provide:

1. Better structure and readability
2. Support for nested configurations
3. Easier management of multiple environments

## Tasks
1. [ ] Choose between TOML and YAML (consider team preferences and existing tooling)
2. [ ] Update `requirements.txt` to include the necessary libraries. `pydantic_settings` [seems to support both](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#other-settings-source) 
3. [ ] Create new configuration files (e.g., `config.toml` or `config.yaml`) for each environment
4. [ ] Update the `Config` class in `globe_news_scraper/config.py` to use the new format
5. [ ] Update `get_config` function to load the appropriate configuration file
6. [ ] Update `Dockerfile` and `docker-compose.yml` to use the new configuration files

## Example Configuration (YAML)
```yaml
log_level: INFO
logging_dir: logs
mongo:
  uri: mongodb://mongo:27017
  db: globe_news_scraper
bing_search:
  endpoint: https://api.bing.microsoft.com/v7.0/news
  subscription_key: your_subscription_key
news_api:
  key: your_news_api_key
max_scraping_workers: 5
```

## Benefits
- Improved readability and maintainability of configuration
- Easier management of complex configurations
- Reduced chance of configuration errors
